name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-13"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjgyMDkwNTQtZDI3Yi00MmQzLWFiNzgtYmVmMDE2NWZiOTgwIiwidGVuYW50X2lkIjoiMmJmZDUyOTQyNDRkZTZkNzFiMDM5NmZiNTM0ZjNmZGU4N2I1MjkzOTQ1ZWUxNzdkNTc5ZDY3MTE0YWYyM2I5MyIsImludGVybmFsX3NlY3JldCI6IjI1ZDBjMzgxLWEzMDItNDc3Yi1hYzY4LTdhOWQxMmUyY2Q0OSJ9.rW5vFjH_RjYpekW88PBzPU7pdy9qwFP-e2fUe1N7hMA"

JWT_SECRET="supersecret"

[observability]
enabled = true
head_sampling_rate = 1
